### Demographic report by gender ###
GET {{baseUrl}}/reports/demographic/gender?questionId=1 HTTP/1.1
content-type: application/json

### Demographic report by postcode ###
GET {{baseUrl}}/reports/demographic/postcode?questionId=7 HTTP/1.1
content-type: application/json

### Demographic report age range ###
GET {{baseUrl}}/reports/demographic/age?questionId=7 HTTP/1.1
content-type: application/json

### Statistic avg weekly responses ###
GET {{baseUrl}}/reports/statistic/avg-weekly-responses HTTP/1.1
content-type: application/json

### Statistic list of users bellow (answered with 0 - not at all) 1 standard deviation from population average ###
GET {{baseUrl}}/reports/statistic/list-users-bellow-sdva HTTP/1.1
content-type: application/json
