### User ###
GET {{baseUrl}}/users?page=0&size=10 HTTP/1.1
content-type: application/json

### User by ID ###
GET {{baseUrl}}/users/9 HTTP/1.1
content-type: application/json

### Add User ###
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "name": "Sancho",
    "gender": "m",
    "postcode": "ls13 2fd",
    "dob": "1992-11-27"
}

### Update User ###
PUT {{baseUrl}}/users/1 HTTP/1.1
content-type: application/json

{
    "name": "Lyubo Gotiniq",
    "gender": "m",
    "postcode": "ls13 2fd",
    "dob": "1992-11-27"
}

### User questions ###
GET {{baseUrl}}/users/1/questions?page=0&size=10 HTTP/1.1
content-type: application/json

### User answers ###
GET {{baseUrl}}/users/answers?page=0&size=10 HTTP/1.1
content-type: application/json

### User answer question ###
POST {{baseUrl}}/users/1/answers HTTP/1.1
content-type: application/json

{
    "questionId": 2,
    "answerId": 2
}

### Update User Role ###
PUT {{baseUrl}}/users/1/role HTTP/1.1
content-type: application/json

{
    "roleId": 1
}
### Delete User Role ###
DELETE {{baseUrl}}/users/1/role HTTP/1.1
content-type: application/json

{
    "roleId": 1
}

### Delete User ###
DELETE {{baseUrl}}/users/9 HTTP/1.1
content-type: application/json